### ISSUE TITLE
does't seem to work with Unity 2019.2

### ISSUE THREAD

**Issue by sebas77** [Unity-Technologies/UnityMixedCallstack#10]
![image](https://user-images.githubusercontent.com/945379/70336359-ebb98900-1840-11ea-92fb-564189873bcf.png)

am I right?

**Comment by sebas77** [comment]
I noticed the vs2019 branch contains an update more recent than this issue. Is there something that could interest me? Does it mean that this code is still being updateD?

**Comment by sebas77** [comment]
@UnityAlex Is this supposed to work with unity 2019? I noticed you updated the project for VS 2019, but I am not able to open the solution. Any help?

**Comment by UnityAlex** [comment]
Oh hey I didn't realize there was an issue open on this tool sorry. I created the vs2019 branch because I was using it and the mixed callstack plugin didn't support it. It looks like the problem you are having isn't related to the version of visual studio but the version of unity that's in use? What versions of Unity were you able to successfully use this with?

**Comment by sebas77** [comment]
Thank you fore the reply. I am actually not sure at this point if it was because of VS or Unity. I am using Unity 2019, I thought the support of MIXED STACK was discontinued, are you saying that it's still supposed to work instead?

**Comment by UnityAlex** [comment]
It should work if you have symbols available. I use this fairly often in my work. Have you been able to get this to work in the past? Most of the people that I know that are using it are internal unity developers.

**Comment by sebas77** [comment]
yes it used to work for me with Unity 2018. I wasn't able to make it work with 2019 when I opened the issue. This code used to be public (meaning not used only internally by unity) when Mike was around. Would you be able to build a release for me like Mike used to do? I strongly believe that a release should be even distributed through the packages system, as this is not useful only for internal unity developers (especially now with all this unsafe code around)

**Comment by sebas77** [comment]
Just to be clear, I asked for a release because I don't know how to build the VS Extension. I would greatly appreciate it. Something like it could be found here, but updated: https://github.com/Unity-Technologies/UnityMixedCallstack/releases. I tried the latest release with 2019.2 and didn't work, maybe it works with 2019.3?

**Comment by UnityAlex** [comment]
I'm attempting to figure out how Mike did the releases. I was going to try to make one with my vs2019 branch. However the only thing that gets you will be support for adding the plugin to visual studio 2019. The plugin for previous versions of visual studio should still work as far as I know. I checked the mono source and it looks like the code is there. Have you tried 2019.3? That's a LTS release and is receiving patches still unlike 2019.2.

**Comment by sebas77** [comment]
OK I will try now again! You mentioned that I need the symbols, do you mean the ones from the Unity symbols server?

**Comment by sebas77** [comment]
oh sorry I think I need the release anyway to be able to use the plugin with 2019? There is, at this point, a strong suspect that I wasn't able to use it because I am using VS 2019. If you are not able to build a release, could you tell me how should I use the plugin?

**Comment by UnityAlex** [comment]
I've added a 2.5 release based off of my vs2019 branch that you can try. It "should" be as simple as installing the .vsix plugin. Let me know if this works (or doesn't) for you.

**Comment by sebas77** [comment]
if I remember correctly, this is all I had to do right?

![image](https://user-images.githubusercontent.com/945379/79762753-0e919900-831b-11ea-8bd4-a4624aea8187.png)

**Comment by sebas77** [comment]
YES IT WORKED! I HAD JUST TO REBOOT!

Thank you one million, I am going to retweet the crap out of this, the world must know :)
