### ISSUE TITLE
Could this approach also work with Windows Performance Analyzer?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Unity-Technologies/UnityMixedCallstack#16]
Right now it's impossible to view Mono stack frames within a recorded WPR trace (they show up as `?!?`, like the [documentation](https://docs.unity3d.com/2018.3/Documentation/uploads/ExpertGuides/Analyzing_your_game_performance_using_Event_Tracing_for_Windows.pdf) says).

Can this tool be extended to allow viewing them in Windows Performance Analyzer?

**Comment by UnityAlex** [comment]
Possibly though I am not familiar with that tool myself unfortunately. In theory if we are able to access the memory address the frame represents we can resolve it to the managed sequence point. At this time it is unlikely that support for this will be added though may be revisited at a later date.

**Comment by joncham** [comment]
I am guessing mono stack frames will work in WPA after this change: https://github.com/Unity-Technologies/mono/pull/1572

**Comment by Holo-Krzysztof** [comment]
> I am guessing mono stack frames will work in WPA after this change: [Unity-Technologies/mono#1572](https://github.com/Unity-Technologies/mono/pull/1572)

Awesome! I'm looking forward to the day this lands in 2020 LTS :)

Edit: for whoever finds this in the future, it's already in 2020.3.38.
