### ISSUE TITLE
Unity2019.4.8f1, Visual Studio 2022 don't work

### ISSUE THREAD

**Issue by kaclok** [Unity-Technologies/UnityMixedCallstack#19]
I set UNITY_MIXED_CALLSTACK environment variable 1, set  Just My Code disabled in visual studio. set the symbol path in vs is http://symbolserver.unity3d.com/. 

 Then, I  made a Unity2019.4.8f1's dump file, and go to Analyse it , but the callstack of managed code is not show

callstack : 

0000012c2897c953()
0000012c25ab4788()
mono-2.0-bdwgc.dll!mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) 行 2809	C
mono-2.0-bdwgc.dll!do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoError * error) 行 2921	C
[内联框架] mono-2.0-bdwgc.dll!mono_runtime_try_invoke(_MonoMethod *) 行 3026	C
mono-2.0-bdwgc.dll!mono_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc) 行 2968	C
Unity.exe!scripting_method_invoke(class ScriptingMethodPtr,class ScriptingObjectPtr,struct ScriptingArguments &,class ScriptingExceptionPtr *,bool)
Unity.exe!ScriptingInvocation::Invoke(class ScriptingExceptionPtr *,bool)
Unity.exe!MonoBehaviour::CallMethodIfAvailable(int)
Unity.exe!MonoBehaviour::CallUpdateMethod(int)
Unity.exe!BaseBehaviourManager::CommonUpdate<class BehaviourManager>(void)
Unity.exe!BehaviourManager::Update(void)
Unity.exe!`InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward()
Unity.exe!ExecutePlayerLoop(struct NativePlayerLoopSystem *)
Unity.exe!ExecutePlayerLoop(struct NativePlayerLoopSystem *)
Unity.exe!PlayerLoop(void)
Unity.exe!PlayerLoopController::UpdateScene(bool)
Unity.exe!Application::TickTimer(void)
Unity.exe!MainMessageLoop()
Unity.exe!WinMain()
Unity.exe!__scrt_common_main_seh()
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()

c# code :

public class NewBehaviourScript : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if(Input.GetKeyDown(KeyCode.A)) {
            int i = 0;
            while(true) {
                ++i;
            }
        }   
    }
}
![Snipaste_2022-08-09_15-42-12](https://user-images.githubusercontent.com/11922982/183594584-40ed42d9-ac38-494b-a672-7b452515e53a.png)

I don't understand why , so i need help

**Comment by UnityAlex** [comment]
Unfortunately you cannot use the mixed callstack plugin on dumpfiles as they require an active mono runtime in order to generate the data required to resolve the managed callstack frames.
